os:
  - linux
  - osx
language: java
jdk:
  - openjdk11
script:
  - ./gradlew clean build

jobs:
  include:
    - stage: release
      script:
        - ./gradlew assemble
      before_deploy:
        - nvm install lts/*
        - yarn install
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
      on:
        branch: master
